
name: Maven Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run tests (headless Firefox)
        run: mvn -q -e -Dtest=LoginTest,LogoutTest clean test
